name: Julia
description: Set-up Julia for use in your pipeline.
author: https://github.com/maleadt
requirements: []
configuration:
  properties:
    version:
      type: string
  additionalProperties: false
