name: Julia
description: Set-up Julia for use in your pipeline.
author: https://github.com/maleadt
requirements: [python3, wget]
configuration:
  properties:
    version:
      type: string
    isolated_depot:
      type: boolean
    persist_depot_dirs:
      type: string
  additionalProperties: false
