steps:
  - label: ":rocket: Launch test matrix"
    agents:
      queue: "juliaecosystem"
    commands: |
      # These variables are available for templating in our child pipelines
      export JULIA_VERSION ARCH AGENT_OS AGENT_ARCH

      function upload_pipelines() {
        ARCH="$$1"
        AGENT_ARCH="$${ARCH}"

        # All our i686 jobs that run on x86_64 hardware
        if [[ "$${ARCH}" == "i686" ]]; then
          AGENT_ARCH="x86_64"
        fi

        # We have a special pipeline for i686
        PIPELINE=".buildkite/run_tests.yml"
        if [[ "$${ARCH}" == "i686" ]]; then
          PIPELINE=".buildkite/run_tests_$${AGENT_OS}32.yml"
        fi

        for JULIA_VERSION in $$2; do
          buildkite-agent pipeline upload "$${PIPELINE}"
        done
      }

      # Launch Linux jobs
      AGENT_OS="linux"
      upload_pipelines x86_64  "1 1.6.0 1.8 nightly"
      upload_pipelines i686    "1 nightly"
      upload_pipelines aarch64 "1 nightly"

      # We don't have a 1.8.X build for ppc64le, so install 1.7 and nightly
      upload_pipelines ppc64le "1.7 nightly"

      # Launch macOS jobs
      AGENT_OS="macos"
      upload_pipelines x86_64  "1 nightly"
      upload_pipelines aarch64 "1 nightly"

      # Launch Windows jobs
      AGENT_OS="windows"
      upload_pipelines x86_64 "1 nightly"
      upload_pipelines i686   "1 nightly"
