self_test_setup: &self_test_setup
  post-checkout: |
    mkdir -p .buildkite/plugins/julia
    cp -Ra hooks plugin.yml README.md .buildkite/plugins/julia/

steps:
  - label: ":julia: ${AGENT_OS?} ${ARCH?} ${JULIA_VERSION?}"
    agents:
      queue: "juliaecosystem"
      os: "${AGENT_OS?}"
      arch: "${AGENT_ARCH?}"
    plugins:
      # Install Julia v1 so we can use Sandbox
      - JuliaCI/julia:
          version: "1.7"
      - staticfloat/sandbox#v2:
         rootfs_url: "https://github.com/JuliaCI/rootfs-images/releases/download/v6.00/agent_linux.armv7l.tar.gz"
         rootfs_treehash: "24ff3a0adda8546251f7a2c3a072b6c53ea0e5e4"
      - staticfloat/metahook#sf/windows_backslashes:
          <<: *self_test_setup
      - "./.buildkite/plugins/julia":
          version: "${JULIA_VERSION?}"
          debug_plugin: "true"
    commands: |
      # If we asked for a nightly version, just check that we got a `1.X`:
      CHECK_VERSION="${JULIA_VERSION?}"
      if [[ "${JULIA_VERSION?}" == "nightly" ]]; then
        CHECK_VERSION="1."
      fi
      [[ "$$(julia --version)" == "julia version $${CHECK_VERSION}"* ]]

      # Always check we got the right architecture
      [[ "$$(julia -E 'Sys.ARCH')" == ":${ARCH?}" ]]
