#!/bin/bash
set -euo pipefail
shopt -s extglob

CACHE_DIR=${BUILDKITE_PLUGIN_JULIA_CACHE_DIR:-${HOME}/.cache/julia-buildkite-plugin}

echo "--- :broom: Performing clean-up"


### Step 1: Remove any code coverage files

echo "Removing coverage files"

# Once JuliaLang/julia#26573 has been fixed, this should no longer be necessary.
find "${CACHE_DIR}"/julia_installs -name "*.jl.*.cov" -type f -delete || true

# Some packages check coverage files in, so only remove writable ones
if [[ "${BUILDKITE_PLUGIN_JULIA_ISOLATED_DEPOT:-true}" == "true" ]]; then
    find "${JULIA_DEPOT_PATH}"/packages -name "*.jl.*.cov" -type f -writable -delete || true
fi


### Step 2: Run `Pkg.gc` to try to reduce the size of the depot.

# since we remove most manifests at the start of each pipeline (cleaning the depot),
# there's no way for Pkg to actually track which artifacts are active, so it doesn't
# matter what we set the collection delay to. Except for triggering removal of orphaned
# resources, which requires multiple invocations of `Pkg.gc` to be effective.

echo "Running Pkg.gc()"
INTVERS="$(tr -d '.' <<<"${BUILDKITE_PLUGIN_JULIA_VERSION:0:3}")"
if [[ "${BUILDKITE_PLUGIN_JULIA_VERSION}" == "nightly" ]] || [[ "${INTVERS}" -gt 16 ]]; then
    GC_ARGS="collect_delay=Second(0), verbose=true"
elif [[ "${INTVERS}" -gt 13 ]]; then
    GC_ARGS="collect_delay=Second(0)"
else
    GC_ARGS=""
fi

julia --color=yes -e "using Pkg, Dates; Pkg.gc(${GC_ARGS})" || true


### Step 3: If the depot is still greater than the hard limit, remove it altogether.
if [[ "${BUILDKITE_PLUGIN_JULIA_ISOLATED_DEPOT:-true}" == "true" ]]; then
    DEPOT_SIZE_HUMAN=$(du --human-readable --summarize "${JULIA_DEPOT_PATH}" | cut -f 1)
    DEPOT_SIZE=$(du --summarize --bytes "${JULIA_DEPOT_PATH}" | cut -f 1)
    DEPOT_HARD_LIMIT="${BUILDKITE_PLUGIN_JULIA_DEPOT_HARD_SIZE_LIMIT:-21474836480}" # 21474836480 bytes = 20 GiB
    echo "The depot size is: ${DEPOT_SIZE_HUMAN}"
    if [[ ${DEPOT_SIZE} -gt ${DEPOT_HARD_LIMIT} ]]; then
        echo "This is greater than the hard limit (${DEPOT_SIZE} > ${DEPOT_HARD_LIMIT} bytes), so we will clear the entire depot"
        rm -rf "${JULIA_DEPOT_PATH}"
        mkdir -p "${JULIA_DEPOT_PATH}"
    fi
fi
