#!/bin/bash
set -euo pipefail
shopt -s extglob

CACHE_DIR=${BUILDKITE_PLUGIN_JULIA_CACHE_DIR:-${HOME}/.cache/julia-buildkite-plugin}

### Step 1: Remove any code coverage files in the `julia_installs directory.
### Once JuliaLang/julia#26573 has been fixed, this should no longer be necessary.

find $(CACHE_DIR)/julia_installs -name "*.jl.*.cov" -type f -delete

### Step 2: Run `Pkg.gc` to try to reduce the size of the cache.

echo "Running Pkg.gc"
julia --color=yes -e 'using Pkg; using Dates; Pkg.gc(; collect_delay=Day(1), force=true, verbose=true)'

### Step 3: If the cache is still greater than the hard limit, clear the entire cache.

CACHE_SIZE=$(du --block-size 1 --summarize $CACHE_DIR | cut -f 1)
CACHE_HARD_LIMIT=21474836480 # 21474836480 bytes = 20 GiB
if [[ $CACHE_SIZE -gt $CACHE_HARD_LIMIT]]; then
    echo "The cache size is $CACHE_SIZE bytes"
    echo "This is greater than the hard limit ($CACHE_HARD_LIMIT bytes), so we will clear the entire cache"
    rm -rf $CACHE_DIR
    mkdir -p $CACHE_DIR
fi
